<?php

if (! defined('ABSPATH')) {
	exit;  // Exit if accessed directly.
}

$config = array(
	'widgets'            => array(
		'is_active' => false,
		'elements'  => array(
			'general-elements'   => array(
				'title'     => 'General',
				'is_active' => false,
				'elements'  => array(

					'button-pro'         => array(
						'label'        => 'Advanced Button Pro',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'setup'        => array('basic'),
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'Button',
							'Advanced Button',
							'Pro Button',
						),
						'order'        => 1,
						'icon'         => 'wcf-icon-Social-Icons',
						'demo_url'     => '#',
						'doc_url'      => '#',
						'youtube_url'  => '',
						'description'  => 'Advanced Button Pro widget with enhanced styling and animation options to create eye-catching call-to-action buttons that drive engagement and conversions on your website.',
					),

					'social-icons'         => array(
						'label'        => 'Social Icons',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'setup'        => array('basic'),
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'social media icons',
							'social links',
							'social follow icons',
							'social network icons',
							'icon links',
							'social buttons',
							'connect icons',
							'share icons',
							'social bar',
							'social profile icons',
						),
						'order'        => 23,
						'icon'         => 'wcf-icon-Social-Icons',
						'demo_url'     => 'https://bricksfly.com/elements/aab-social-icons',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/social-icons/',
						'youtube_url'  => '',
						'description'  => 'Link your social accounts and customize the look to perfectly match your branding.',
					),
					'brand-slider'         => array(
						'label'        => 'Brand Slider',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'setup'        => array('basic'),
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'logo carousel',
							'brand showcase',
							'partner logo slider',
							'client logo slider',
							'sponsor logos',
							'logo scrolling',
							'brand carousel',
							'company logos',
							'rotating brand logos',
							'logo showcase slider',
						),
						'order'        => 13,
						'icon'         => 'wcf-icon-Brand-Slider',
						'demo_url'     => 'https://bricksfly.com/elements/aab-brand-slider',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/brand-slider/',
						'youtube_url'  => '',
						'description'  => 'Boost credibility and visibility by highlighting trusted logos with a smooth, auto-scrolling slider.',
					),
					'counter'              => array(
						'label'        => 'Counter',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'setup'        => array('basic'),
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'number counter',
							'animated counter',
							'stats counter',
							'milestone counter',
							'counting numbers',
							'fun facts counter',
							'counter animation',
							'numeric counter',
							'counter up',
							'number animation',
						),
						'order'        => 28,
						'icon'         => 'wcf-icon-Counter',
						'demo_url'     => 'https://bricksfly.com/elements/aab-counter',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/counter/',
						'youtube_url'  => '',
						'description'  => 'Impress visitors with live stats and milestones using fully animated number counters.',
					),
					'progressbar'          => array(
						'label'        => 'Progress Bar',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'setup'        => array('basic'),
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'progress bar',
							'progressbar',
							'skill bar',
							'percentage bar',
							'circle progress',
							'line progress',
							'dot progress',
							'animated progress',
							'progress indicator',
							'loading bar',
						),
						'order'        => 29,
						'icon'         => 'wcf-icon-Progress-Bar',
						'demo_url'     => 'https://bricksfly.com/elements/aab-progress-bar',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/progress-bar/',
						'youtube_url'  => '',
						'description'  => 'Visualize stats and skills with animated line, circle, or dot-style progress bars.',
					),
					'icon-box'             => array(
						'label'        => 'Icon Box',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'setup'        => array('basic'),
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'icon with text',
							'feature box',
							'service icon box',
							'icon title description',
							'icon content block',
							'info box',
							'icon highlight',
							'icon description widget',
							'icon showcase',
							'icon text block',
						),
						'order'        => 12,
						'icon'         => 'wcf-icon-Icon-Box',
						'demo_url'     => 'https://bricksfly.com/elements/aab-icon-box',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/icon-box/',
						'youtube_url'  => '',
						'description'  => 'Refine your content presentation with flexible icon styling, typography, and layout options.',
					),
					'testimonial-1'        => array(
						'label'        => 'Testimonial',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'setup'        => array('basic'),
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'testimonial block',
							'client review',
							'customer feedback',
							'testimonial section',
							'testimonial slider',
							'review widget',
							'client comment',
							'customer opinion',
							'feedback carousel',
							'testimonial display',
						),
						'order'        => 40,
						'icon'         => 'wcf-icon-Testimonial',
						'demo_url'     => 'https://bricksfly.com/elements/aab-testimonial',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/testimonial/',
						'youtube_url'  => '',
						'description'  => 'Share real stories and success quotes using animated testimonial sliders and flexible content settings.',
					),
					'testimonial-2'        => array(
						'label'        => 'Classic Testimonial',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'simple testimonial',
							'basic testimonial widget',
							'client review section',
							'traditional testimonial',
							'feedback block',
							'customer opinion',
							'classic review slider',
							'client comment block',
							'basic testimonial slider',
							'review display',
						),
						'order'        => 57,
						'icon'         => 'wcf-icon-Testimonial-2',
						'demo_url'     => 'https://bricksfly.com/elements/aab-classic-testimonial',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/classic-testimonial/',
						'youtube_url'  => '',
						'description'  => 'Showcase real stories and client praise with a sleek, responsive testimonial carousel.',
					),
					'testimonial-3'        => array(
						'label'        => 'Modern Testimonial',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'testimonial slider',
							'client feedback',
							'customer review',
							'testimonial showcase',
							'modern testimonial design',
							'testimonial carousel',
							'review block',
							'client testimonial section',
							'stylish testimonials',
							'feedback widget',
						),
						'order'        => 31,
						'icon'         => 'wcf-icon-Testimonial-3',
						'demo_url'     => 'https://bricksfly.com/elements/aab-modern-testimonial',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/modern-testimonial/',
						'youtube_url'  => '',
						'description'  => 'Highlight customer feedback with modern layouts, smooth sliders, and customizable design elements.',
					),

					'team'                 => array(
						'label'        => 'Team',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'team members',
							'staff showcase',
							'employee profiles',
							'team profile widget',
							'meet the team',
							'staff directory',
							'team photo gallery',
							'team bio section',
							'company team display',
							'team showcase slider',
						),
						'order'        => 48,
						'setup'        => array('basic'),
						'icon'         => 'wcf-icon-Team',
						'demo_url'     => 'https://bricksfly.com/elements/aab-team',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/team/',
						'youtube_url'  => '',
						'description'  => 'Help visitors meet your team with photos, job titles, and clickable social media icons.',
					),
					'timeline'             => array(
						'label'        => 'Timeline',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'vertical timeline',
							'horizontal timeline',
							'event timeline',
							'history timeline',
							'animated timeline',
							'project timeline',
							'story timeline',
							'timeline with icons',
							'content timeline',
							'interactive timeline',
						),
						'order'        => 18,
						'icon'         => 'wcf-icon-Timeline',
						'demo_url'     => 'https://bricksfly.com/elements/aab-timeline',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/timeline/',
						'youtube_url'  => '',
						'description'  => 'Use animated timelines to present events or project stages in a clear, organized progression.',
					),
					'floating-elements'    => array(
						'label'        => 'Floating',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'floating animation',
							'float effect',
							'hover floating element',
							'floating object',
							'animated float',
							'float on scroll',
							'moving floating element',
							'floating icon',
							'floating image',
							'floating graphic animation',
						),
						'order'        => 15,
						'setup'        => array('basic'),
						'icon'         => 'wcf-icon-Floating-Elements',
						'demo_url'     => 'https://bricksfly.com/elements/aab-floating-elements',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/floating-elements/',
						'youtube_url'  => '',
						'description'  => 'Add floating items to your page, such as buttons or icons, that stay in view as users scroll',
					),
				),
			),
			'animation-elements' => array(
				'title'     => 'Animations',
				'is_active' => false,
				'elements'  => array(
					'animated-heading' => array(
						'label'        => 'Animated Heading',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'animated heading',
							'heading animation',
							'moving title',
							'headline effect',
							'scrolling heading',
							'fade-in heading',
							'dynamic title',
							'heading reveal',
							'stylish heading',
							'creative title animation',
						),
						'order'        => 6,
						'icon'         => 'wcf-icon-Animated-Heading',
						'demo_url'     => 'https://bricksfly.com/elements/aab-animated-heading/',
						'doc_url'      => 'https://bricksfly.com/docs/animations-widgets/animated-heading/',
						'youtube_url'  => '',
						'description'  => 'Add stunning movement to your headlines and capture attention in just a second.',
					),
				),
			),
			'hf-elements'        => array(
				'title'     => 'Header & Footer',
				'is_active' => false,
				'elements'  => array(
					'animated-offcanvas' => array(
						'label'        => 'Animated Off-Canvas',
						'is_active'    => false,
						'location'     => array(
							'cTab' => 'all',
						),
						'is_upcoming'  => false,
						'is_pro'       => true,
						'is_extension' => false,
						'keywords'     => array(
							'off-canvas menu',
							'hidden menu',
							'slide-out panel',
							'sidebar menu',
							'mobile menu drawer',
							'offscreen navigation',
							'drawer menu',
							'slide-in widget',
							'off-canvas sidebar',
							'hidden content panel',
						),
						'order'        => 10,
						'icon'         => 'wcf-icon-Animated-Off-Canvas',
						'demo_url'     => 'https://bricksfly.com/elements/aab-animated-off-canvas/',
						'doc_url'      => 'https://bricksfly.com/docs/header-footer-widgets/animated-off-canvas/',
						'youtube_url'  => '',
						'description'  => 'Captivate your audience with stunning off-canvas reveals that keep users engaged longer on site!',
					),
				),
			),
			// 'slider'             => array(
			// 	'title'     => 'Slider',
			// 	'is_active' => false,
			// 	'elements'  => array(),
			// ),
			'dynamic-elements'   => array(
				'title'     => 'Dynamic',
				'is_active' => false,
				'elements'  => array(
					'post-social-share'  => array(
						'label'        => 'Social Share',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'share buttons',
							'social sharing',
							'share post',
							'share to social media',
							'share widget',
							'social icons share',
							'content share',
							'social media sharing',
							'share blog post',
							'share article buttons',
						),
						'order'        => 91,
						'icon'         => 'wcf-icon-Post-Social-Share',
						'demo_url'     => 'https://bricksfly.com/docs/dynamic-widgets/social-share/',
						'doc_url'      => 'https://bricksfly.com/docs/dynamic-widgets/social-share/',
						'youtube_url'  => '',
						'description'  => 'Customize social share icons to match your design and encourage content sharing with ease.',
					),
					'post-meta'          => array(
						'label'        => 'Post Meta',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'post meta',
							'meta data',
							'post info',
							'author',
							'category',
							'date',
							'reading time',
							'comments count',
							'view count',
							'time ago',
						),
						'order'        => 92,
						'icon'         => 'wcf-icon-Post-Social-Share',
						'demo_url'     => 'https://bricksfly.com/docs/dynamic-widgets/post-meta/',
						'doc_url'      => 'https://bricksfly.com/docs/dynamic-widgets/post-meta/',
						'youtube_url'  => '',
						'description'  => 'Display rich post meta — author, date, categories, comments, reading time, view count, and more.',
					),
					'video-story'        => array(
						'label'        => 'Video Story',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => false,
						'is_upcoming'  => false,
						'keywords'     => array(
							'video highlights',
							'story video',
							'vertical video',
							'social media story video',
							'video reels',
							'short video story',
							'video status',
							'quick video showcase',
							'mobile story video',
							'animated story video',
						),
						'order'        => 47,
						'icon'         => 'wcf-icon-Video-Box',
						'demo_url'     => 'https://bricksfly.com/elements/aab-video-story',
						'doc_url'      => 'https://bricksfly.com/docs/general-widgets/video-story/',
						'youtube_url'  => '',
						'description'  => 'Share engaging video content with smooth transitions to tell your story effectively.',
					),
				),
			),
			// 'form-elements'      => array(
			// 	'title'     => 'Form Widgets',
			// 	'is_active' => false,
			// 	'elements'  => array(),
			// ),
			'video-elements'     => array(
				'title'     => 'Video',
				'is_active' => false,
				'elements'  => array(
					'video-popup'      => array(
						'label'        => 'Video Popup',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => true,
						'is_extension' => true,
						'is_upcoming'  => false,
						'keywords'     => array(
							'video lightbox',
							'popup video player',
							'video overlay',
							'video modal',
							'play video popup',
							'video launch window',
							'fullscreen video popup',
							'click to play video',
							'video in popup',
							'embedded popup video',
						),
						'order'        => 50,
						'setup'        => array('basic'),
						'icon'         => 'wcf-icon-Video-Popup',
						'demo_url'     => 'https://bricksfly.com/elements/aab-video-popup',
						'doc_url'      => 'https://bricksfly.com/docs/video-widgets/video-popup/',
						'youtube_url'  => '',
						'description'  => 'Use the Video Popup Widget to display videos in popups, making content more engaging.',
					),
					'video-box'        => array(
						'label'        => 'Video Box',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => true,
						'is_upcoming'  => false,
						'keywords'     => array(
							'video embed',
							'video player box',
							'video content block',
							'featured video',
							'video showcase',
							'embedded video widget',
							'video display',
							'video highlight',
							'video container',
							'video section',
						),
						'order'        => 55,
						'icon'         => 'wcf-icon-Video-Box',
						'demo_url'     => 'https://bricksfly.com/elements/aab-video-box',
						'doc_url'      => 'https://bricksfly.com/docs/video-widgets/video-box/',
						'youtube_url'  => '',
						'description'  => 'Elevate your website’s look by incorporating a video box that blends seamlessly with your style.',
					),
					'video-mask'       => array(
						'label'        => 'Video Mask',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => true,
						'is_upcoming'  => false,
						'keywords'     => array(
							'masked video',
							'shape video mask',
							'video overlay shape',
							'custom video mask',
							'video frame effect',
							'masked video effect',
							'video inside shape',
							'creative video mask',
							'shape overlay video',
							'styled video mask',
						),
						'order'        => 56,
						'icon'         => 'wcf-icon-Video-Mask',
						'demo_url'     => 'https://bricksfly.com/elements/aab-video-mask',
						'doc_url'      => 'https://bricksfly.com/docs/video-widgets/video-mask/',
						'youtube_url'  => '',
						'description'  => 'Use the Video Mask Widget to bring artistic, interactive flair to your sites videos.',
					),
					'youtube-videos'   => array(
						'label'        => 'Youtube Video',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => true,
						'is_extension' => true,
						'is_upcoming'  => false,
						'keywords'     => array(
							'youtube embed',
							'youtube player',
							'youtube video block',
							'youtube content',
							'youtube showcase',
							'youtube gallery',
							'video from youtube',
							'youtube section',
							'youtube feed widget',
							'youtube integration',
						),
						'order'        => 77,
						'icon'         => 'wcf-icon-Video-Mask',
						'demo_url'     => 'https://bricksfly.com/elements/youtube-video-widget-for-elementor/',
						'doc_url'      => 'https://bricksfly.com/docs/video-widgets/youtube-video/',
						'youtube_url'  => '',
						'description'  => 'Use the Youtube Video Widget to bring artistic, interactive flair to your sites videos.',
					),
					'scrollable-video' => array(
						'label'        => 'Scrollable Video',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => true,
						'is_extension' => true,
						'is_upcoming'  => false,
						'keywords'     => array(
							'scrollable video',
							'scroll video',
							'gsap scroll video',
							'scrolltrigger video',
							'video on scroll',
							'pin video',
							'frame by frame video',
							'scroll triggered video',
							'video scrub',
							'scroll animation video',
						),
						'order'        => 78,
						'icon'         => 'wcf-icon-Video-Mask',
						'demo_url'     => 'https://bricksfly.com/elements/aab-scrollable-video',
						'doc_url'      => 'https://bricksfly.com/docs/video-widgets/scrollable-video/',
						'youtube_url'  => '',
						'description'  => 'Use the Scrollable Video Widget to play a video frame-by-frame as the user scrolls.',
					),

					'video-box-slider' => array(
						'label'        => 'Video Box Slider',
						'location'     => array(
							'cTab' => 'all',
						),
						'is_active'    => false,
						'is_pro'       => false,
						'is_extension' => true,
						'is_upcoming'  => false,
						'keywords'     => array(
							'video slider',
							'video carousel',
							'swiper video slider',
							'video box carousel',
							'video gallery slider',
							'video popup slider',
							'youtube slider',
							'vimeo slider',
							'play video slider',
							'video showcase slider',
						),
						'order'        => 78,
						'icon'         => 'wcf-icon-Video-Box',
						'demo_url'     => 'https://bricksfly.com/elements/aab-video-box-slider',
						'doc_url'      => 'https://bricksfly.com/docs/video-widgets/video-box-slider/',
						'youtube_url'  => '',
						'description'  => 'Showcase multiple videos in a Swiper-powered carousel with click-to-play popups and rich styling.',
					),
				),
			),
			'advanced-elements'  => array(
				'title'     => 'Advanced',
				'is_active' => false,
				'elements'  => array(
					'image-accordion'       => array(
						'label'        => 'Image Accordion',
						'is_active'    => false,
						'location'     => array(
							'cTab' => 'all',
						),
						'is_upcoming'  => false,
						'is_pro'       => false,
						'is_extension' => false,
						'keywords'     => array(
							'accordion gallery',
							'image toggle',
							'expanding image',
							'collapsible image section',
							'hover image accordion',
							'interactive image accordion',
							'image expand effect',
							'image stack accordion',
							'sliding image accordion',
							'image reveal accordion',
						),
						'order'        => 39,
						'icon'         => 'wcf-icon-Image-Accordion',
						'demo_url'     => 'https://bricksfly.com/elements/aab-image-accordion',
						'doc_url'      => 'https://bricksfly.com/docs/advanced-widgets/image-accordion/',
						'youtube_url'  => '',
						'description'  => 'Present images creatively with collapsible sections, enhancing user experience and saving screen space.',
					),
					'toggle-switch'         => array(
						'label'        => 'Toggle Switch',
						'is_active'    => false,
						'location'     => array(
							'cTab' => 'all',
						),
						'is_upcoming'  => false,
						'is_pro'       => false,
						'is_extension' => false,
						'keywords'     => array(
							'toggle switch',
							'switcher',
							'tab toggle',
							'pricing toggle',
							'monthly yearly',
							'content switcher',
							'template switcher',
						),
						'order'        => 42,
						'icon'         => 'wcf-icon-Advanced-Accordion',
						'demo_url'     => '#',
						'doc_url'      => '#',
						'youtube_url'  => '',
						'description'  => 'Switch between two content panes (or saved Bricks templates) with a stylish toggle.',
					),
					'draggable-items'       => array(
						'label'        => 'Draggable Items',
						'is_active'    => false,
						'location'     => array(
							'cTab' => 'all',
						),
						'is_upcoming'  => false,
						'is_pro'       => false,
						'is_extension' => false,
						'keywords'     => array(
							'draggable',
							'drag',
							'drag and drop',
							'interactive items',
							'movable items',
							'sortable items',
							'drag interaction',
							'draggable cards',
							'draggable tags',
							'interactive drag',
						),
						'order'        => 43,
						'icon'         => 'wcf-icon-Animation',
						'demo_url'     => '#',
						'doc_url'      => '#',
						'youtube_url'  => '',
						'description'  => 'Let visitors drag and rearrange interactive items freely around the page.',
					),
				),
			),
		),
	),
	'extensions'         => array(
		'is_active' => false,
		'elements'  => array(
			'general-extensions' => array(
				'title'     => 'General Extensions',
				'is_active' => false,
				'elements' => array(

					'general-settings' => array(
						'title'     => 'General Settings',
						'doc_url'   => '',
						'is_pro'    => true,
						'is_active' => false,
						'elements'  => array(
							'tilt-effect'         => array(
								'label'        => 'Tilt Effect',
								'location'     => array(
									'cTab'     => 'general',
									'pluginId' => 'general-extensions',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Tilt-Effect',
								'demo_url'     => 'https://bricksfly.com/extensions/tilt-effect/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/tilt-effect/',
								'youtube_url'  => '',
							),
							'advanced-tooltip'    => array(
								'label'        => 'Advanced Tooltip',
								'location'     => array(
									'cTab'     => 'general',
									'pluginId' => 'general-extensions',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Advanced-Tooltip',
								'demo_url'     => 'https://bricksfly.com/extensions/advanced-tooltip/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/advanced-tooltip/',
								'youtube_url'  => '',
							),
							'wrapper-link'        => array(
								'label'        => 'Wrapper Link',
								'location'     => array(
									'cTab'     => 'general',
									'pluginId' => 'general-extensions',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Wrapper-Link',
								'demo_url'     => 'https://bricksfly.com/extensions/wrapper-link/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/wrapper-link/',
								'youtube_url'  => '',
							),
							'live-copy'           => array(
								'label'        => 'Live Copy',
								'location'     => array(
									'cTab'     => 'general',
									'pluginId' => 'general-extensions',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Live-Copy',
								'demo_url'     => 'https://bricksfly.com/extensions/live-copy/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/live-copy/',
								'youtube_url'  => '',
							),
							// 'popup'        => array(
							// 	'label'        => 'Popup',
							// 	'location'     => array(
							// 		'cTab'     => 'general',
							// 		'pluginId' => 'general-extensions',
							// 	),
							// 	'is_pro'       => true,
							// 	'is_active'    => false,
							// 	'is_extension' => false,
							// 	'is_upcoming'  => false,
							// 	'setup'        => array('basic'),
							// 	'icon'         => 'wcf-icon-Wrapper-Link',
							// 	'demo_url'     => 'https://bricksfly.com/extensions/popup/',
							// 	'doc_url'      => 'https://bricksfly.com/docs/general-extensions/popup/',
							// 	'youtube_url'  => '',
							// ),
						),
					),

					'site-settings' => array(
						'title'     => 'Site Settings',
						'doc_url'   => '',
						'is_pro'    => true,
						'is_active' => false,
						'elements'  => array(
							'settings-preloader'       => array(
								'label'        => 'Preloader',
								'location'     => array(
									'cTab' => 'general',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_sitesettings' => true,
								'is_upcoming'  => false,
								'icon'         => 'wcf-icon-settings-preloader',
								'demo_url'     => 'https://bricksfly.com/extensions/preloader/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/preloader/',
								'youtube_url'  => '',
							),
							'settings-cursor'       => array(
								'label'        => 'Cursor',
								'location'     => array(
									'cTab' => 'general',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_sitesettings' => true,
								'is_upcoming'  => false,
								'icon'         => 'wcf-icon-settings-cursor',
								'demo_url'     => 'https://bricksfly.com/extensions/cursor/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/cursor/',
								'youtube_url'  => '',
							),
							'settings-scroll-indicator'       => array(
								'label'        => 'Scroll Indicator',
								'location'     => array(
									'cTab' => 'general',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_sitesettings' => true,
								'is_upcoming'  => false,
								'icon'         => 'wcf-icon-settings-scroll-indicator',
								'demo_url'     => 'https://bricksfly.com/extensions/scroll-indicator/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/scroll-indicator/',
								'youtube_url'  => '',
							),
							'settings-scroll-to-top'       => array(
								'label'        => 'Scroll To Top',
								'location'     => array(
									'cTab' => 'general',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_sitesettings' => true,
								'is_upcoming'  => false,
								'icon'         => 'wcf-icon-settings-scroll-to-top',
								'demo_url'     => 'https://bricksfly.com/extensions/scroll-to-top/',
								'doc_url'      => 'https://bricksfly.com/docs/general-extensions/scroll-to-top/',
								'youtube_url'  => '',
							),
						),
					),
				),
			),
			'gsap-extensions'    => array(
				'title'     => 'GSAP Extensions',
				'is_active' => false,

				'elements'  => array(
					'aab-smooth-scroller' => array(
						'title'     => 'Scroll Smoother',
						'doc_url'   => 'https://support.crowdytheme.com/docs/advanced-settings/advanced-settings/wcf-custom-css/',
						'is_pro'    => true,
						'is_active' => false,
						'elements'  => array(
							'animation-effects'       => array(
								'label'        => 'Animation',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'aab-smooth-scroller',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic', 'advance'),
								'icon'         => 'wcf-icon-Animation',
								'demo_url'     => 'https://bricksfly.com/extensions/animation/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/animation/',
								'youtube_url'  => '',
							),
							'pin-element'             => array(
								'label'        => 'Sticky/Pin Element',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'aab-smooth-scroller',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic', 'advance'),
								'icon'         => 'wcf-icon-Pin-Elements',
								'demo_url'     => 'https://bricksfly.com/extensions/sticky-pin-element/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/sticky-pin-element/',
								'youtube_url'  => '',
							),
							'text-animation-effects'  => array(
								'label'        => 'Text Animation',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'aab-smooth-scroller',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'icon'         => 'wcf-icon-Text-Animation',
								'demo_url'     => 'https://bricksfly.com/extensions/text-animation/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/text-animation/',
								'youtube_url'  => '',
							),
							'image-animation-effects' => array(
								'label'        => 'Image Animation',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'aab-smooth-scroller',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'icon'         => 'wcf-icon-Image-Animation',
								'demo_url'     => 'https://bricksfly.com/extensions/image-animation/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/image-animation/',
								'youtube_url'  => '',
							),
							'parallax-effect'         => array(
								'label'        => 'Parallax Effect',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'aab-smooth-scroller',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Animation',
								'demo_url'     => 'https://bricksfly.com/extensions/parallax-effect/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/parallax-effect/',
								'youtube_url'  => '',
							),
						),
					),
					'effect' => array(
						'title'     => 'Effects',
						'doc_url'   => '#',
						'is_pro'    => true,
						'is_active' => false,
						'elements'  => array(
							'cursor-hover-effect' => array(
								'label'        => 'Cursor Hover Effect',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'effect',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Cursor-Hover-Effect',
								'demo_url'     => 'https://bricksfly.com/extensions/cursor-hover-effect/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/cursor-hover-effect/',
								'youtube_url'  => '',
							),
							'hover-effect-image'  => array(
								'label'        => 'Image Reveal on Hover',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'effect',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Image-Hover-Effect',
								'demo_url'     => 'https://bricksfly.com/extensions/image-reveal-on-hover/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/image-reveal-on-hover/',
								'youtube_url'  => '',
							),
							'cursor-move-effect'  => array(
								'label'        => 'Cursor Move Effect',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'effect',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Cursor-Move-Effect',
								'demo_url'     => 'https://bricksfly.com/extensions/cursor-move-effect/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/cursor-move-effect/',
								'youtube_url'  => '',
							),
						),
					),
					'scroll-trigger' => array(
						'title'     => 'ScrollTrigger',
						'doc_url'   => 'https://support.crowdytheme.com/docs/advanced-settings/advanced-settings/wcf-custom-css/',
						'is_pro'    => true,
						'is_active' => false,
						'elements'  => array(
							'horizontal-scroll' => array(
								'label'        => 'Horizontal',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'scroll-trigger',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Horizontal',
								'demo_url'     => 'https://bricksfly.com/extensions/horizontal/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/horizontal/',
								'youtube_url'  => '',
							),
							'scrollto'          => array(
								'label'        => 'ScrollTo',
								'location'     => array(
									'cTab'     => 'gsap',
									'pluginId' => 'scroll-trigger',
								),
								'is_pro'       => true,
								'is_active'    => false,
								'is_extension' => false,
								'is_upcoming'  => false,
								'setup'        => array('basic'),
								'icon'         => 'wcf-icon-Horizontal',
								'demo_url'     => 'https://bricksfly.com/extensions/scroll-to/',
								'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/scroll-to/',
								'youtube_url'  => '',
							),
						),
					),
					// 'flip' => array(
					// 	'title'     => 'Flips',
					// 	'doc_url'   => 'https://support.crowdytheme.com/docs/advanced-settings/advanced-settings/wcf-custom-css/',
					// 	'is_pro'    => true,
					// 	'is_active' => false,
					// 	'elements'  => array(
					// 		'portfolio-filter' => array(
					// 			'label'        => 'Portfolio Filter',
					// 			'location'     => array(
					// 				'cTab'     => 'gsap',
					// 				'pluginId' => 'flip',
					// 			),
					// 			'is_pro'       => false,
					// 			'is_active'    => true,
					// 			'is_extension' => true,
					// 			'is_upcoming'  => false,
					// 			'icon'         => 'wcf-icon-Portfolio-Filter',
					// 			'demo_url'     => 'https://bricksfly.com/docs/gsap-extensions/portfolio-filter/',
					// 			'doc_url'      => 'https://bricksfly.com/docs/gsap-extensions/portfolio-filter/',
					// 			'youtube_url'  => '',
					// 		),
					// 	),
					// ),


				),
			),
		),
	),
	'integrations'       => array(
		'plugins' => array(
			'title'    => 'Plugins',
			'elements' => array(
				// The React bundle keys off "bricksfly-pro"
				// when deciding which plugin counts as "the Pro". We keep that
				// key for UI compatibility but point the basename at the
				// Bricks Pro plugin so the detected state is correct.
				'bricksfly-pro' => array(
					'label'        => 'BricksFly Pro',
					'basename'     => 'bricksfly-pro/bricksfly-pro.php',
					'source'       => 'custom',
					'is_pro'       => false,
					'slug'         => '',
					'download_url' => '',
				),
			),
		),
		'library' => array(
			'title'    => 'Library',
			'elements' => array(
				'gsap-library' => array(
					'title'     => 'GSAP Library',
					'is_pro'    => true,
					'is_active' => false,
					'elements'  => array(
						'draggable'          => array(
							'label'     => 'Draggable',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/Draggable',
						),
						'easel'              => array(
							'label'     => 'Easel',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/EaselPlugin',
						),
						'flip'               => array(
							'label'     => 'Flip',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/Flip',
						),
						'motion-path'        => array(
							'label'     => 'MotionPath',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/MotionPathPlugin',
						),
						'observer'           => array(
							'label'     => 'Observer',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/Observer',
						),
						'pixi'               => array(
							'label'     => 'Pixi',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/PixiPlugin',
						),
						'scroll-to'          => array(
							'label'     => 'ScrollTo',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/ScrollToPlugin',
						),
						'scroll-trigger'     => array(
							'label'     => 'ScrollTrigger',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/ScrollTrigger/?page=1',
						),
						'text'               => array(
							'label'     => 'Text',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/TextPlugin',
						),
						'draw-svg'           => array(
							'label'     => 'DrawSVG',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/DrawSVGPlugin',
						),
						'physics-2d'         => array(
							'label'     => 'Physics2D',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/Physics2DPlugin',
						),
						'physics-props'      => array(
							'label'     => 'PhysicsProps',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/PhysicsPropsPlugin',
						),
						'scramble-text'      => array(
							'label'     => 'ScrambleText',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/ScrambleTextPlugin',
						),
						'gs-dev-tools'       => array(
							'label'     => 'GSDevTools',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/GSDevTools',
						),
						'inertia'            => array(
							'label'     => 'Inertia',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/InertiaPlugin',
						),
						'morph-svg'          => array(
							'label'     => 'MorphSVG',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/MorphSVGPlugin',
						),
						'motion-path-helper' => array(
							'label'     => 'MotionPathHelper',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/MotionPathHelper',
						),
						'scroll-smoother'    => array(
							'label'     => 'ScrollSmoother',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/ScrollSmoother',
						),
						'split-text'         => array(
							'label'     => 'SplitText',
							'is_pro'    => true,
							'is_active' => false,
							'icon'      => 'wcf-icon-Animation-Builder',
							'doc_url'   => 'https://gsap.com/docs/v3/Plugins/SplitText',
						),
					),
				),
			),
		),
	),
);

$dashboard_pro_widget_slugs = array(
	'animated-heading',
	'icon-box',
	'social-icons',
	'counter',
	'testimonial-1',
	'button-pro',
);
$widget_index = array();
if (! empty($config['widgets']['elements']) && is_array($config['widgets']['elements'])) {
	foreach ($config['widgets']['elements'] as $group) {
		if (empty($group['elements']) || ! is_array($group['elements'])) {
			continue;
		}
		foreach ($group['elements'] as $slug => $widget) {
			$widget_index[$slug] = $widget;
		}
	}
}
$dashboard_pro_widgets = array();
foreach ($dashboard_pro_widget_slugs as $slug) {
	if (isset($widget_index[$slug])) {
		$dashboard_pro_widgets[$slug] = $widget_index[$slug];
	}
}
$config['dashboardProWidget'] = $dashboard_pro_widgets;

$GLOBALS['aab_addons_config'] = $config;
